version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # - FLASK_APP=/app/__init__.py
      - FLASK_APP=/run.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
  
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=noisense
      - MYSQL_DATABASE=noisense
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
